plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'org.haina2410.motivana'
version = '0.1.0'

android {
  namespace 'org.haina2410.motivana.wallpaper'
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
  sourceSets {
    main.assets.srcDirs += "${project.rootDir}/../assets"
  }
}

dependencies {
  implementation 'androidx.work:work-runtime-ktx:2.10.3'
  testImplementation 'junit:junit:4.13.2'
}
